
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'asterisk char_keyword colon const_keyword field_keyword format_keyword id_keyword int_keyword name name_keyword new_line number offset_keyword pid_t_keyword semicolon short_keyword signed_keyword size_keyword size_t_keyword struct_keyword unsigned_keywordprogram : syscall_name                  syscall_id                  format_dec                  parameters format_dec : format_keyword colonsyscall_name : name_keyword colon name syscall_id : id_keyword colon numberparameters : parameter\n                    | parameters parameterparameter : field_keyword colon data_type name semicolon     offset_keyword colon number semicolon     size_keyword colon number semicolon     signed_keyword colon number semicolondata_type : int_keyword\n                   | short_keyword\n                   | char_keyword\n                   | size_t_keyword\n                   | pid_t_keyword\n                   | unsigned_keyword data_type\n                   | const_keyword data_type\n                   | data_type asterisk\n                   | struct_keyword name'
    
_lr_action_items = {'name_keyword':([0,],[3,]),'$end':([1,11,12,16,44,],[0,-1,-5,-6,-7,]),'id_keyword':([2,10,],[5,-3,]),'colon':([3,5,8,13,33,37,41,],[6,9,14,17,34,38,42,]),'format_keyword':([4,15,],[8,-4,]),'name':([6,18,19,20,21,22,23,26,28,29,30,31,],[10,27,-8,-9,-10,-11,-12,31,-15,-13,-14,-16,]),'field_keyword':([7,11,12,14,16,44,],[13,13,-5,-2,-6,-7,]),'number':([9,34,38,42,],[15,35,39,43,]),'int_keyword':([17,24,25,],[19,19,19,]),'short_keyword':([17,24,25,],[20,20,20,]),'char_keyword':([17,24,25,],[21,21,21,]),'size_t_keyword':([17,24,25,],[22,22,22,]),'pid_t_keyword':([17,24,25,],[23,23,23,]),'unsigned_keyword':([17,24,25,],[24,24,24,]),'const_keyword':([17,24,25,],[25,25,25,]),'struct_keyword':([17,24,25,],[26,26,26,]),'asterisk':([18,19,20,21,22,23,28,29,30,31,],[28,-8,-9,-10,-11,-12,-15,28,28,-16,]),'semicolon':([27,35,39,43,],[32,36,40,44,]),'offset_keyword':([32,],[33,]),'size_keyword':([36,],[37,]),'signed_keyword':([40,],[41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'syscall_name':([0,],[2,]),'syscall_id':([2,],[4,]),'format_dec':([4,],[7,]),'parameters':([7,],[11,]),'parameter':([7,11,],[12,16,]),'data_type':([17,24,25,],[18,29,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> syscall_name syscall_id format_dec parameters','program',4,'p_program','main.py',143),
  ('format_dec -> format_keyword colon','format_dec',2,'p_format_dec','main.py',158),
  ('syscall_name -> name_keyword colon name','syscall_name',3,'p_syscall_name','main.py',162),
  ('syscall_id -> id_keyword colon number','syscall_id',3,'p_syscall_id','main.py',167),
  ('parameters -> parameter','parameters',1,'p_parameters','main.py',171),
  ('parameters -> parameters parameter','parameters',2,'p_parameters','main.py',172),
  ('parameter -> field_keyword colon data_type name semicolon offset_keyword colon number semicolon size_keyword colon number semicolon signed_keyword colon number semicolon','parameter',17,'p_parameter','main.py',185),
  ('data_type -> int_keyword','data_type',1,'p_data_type','main.py',195),
  ('data_type -> short_keyword','data_type',1,'p_data_type','main.py',196),
  ('data_type -> char_keyword','data_type',1,'p_data_type','main.py',197),
  ('data_type -> size_t_keyword','data_type',1,'p_data_type','main.py',198),
  ('data_type -> pid_t_keyword','data_type',1,'p_data_type','main.py',199),
  ('data_type -> unsigned_keyword data_type','data_type',2,'p_data_type','main.py',200),
  ('data_type -> const_keyword data_type','data_type',2,'p_data_type','main.py',201),
  ('data_type -> data_type asterisk','data_type',2,'p_data_type','main.py',202),
  ('data_type -> struct_keyword name','data_type',2,'p_data_type','main.py',203),
]
